<div id="boxext">
Completare i campi sottostanti. I campi contrassegnati da <img src="./immagini/popcorn22.gif" id="asterisco"> sono obbligatori.<br><br>

            
     <img src="./immagini/popcorn22.gif" id="asterisco"><label>Username:</label> <input type="text" id="username" placeholder="Username" size="20" maxlength="40" value="{if isset($dati_registrazione.username)}{$dati_registrazione.username}{/if}" onchange="validazioneadmin('username');"><div id="risultato1">{if isset($dati_errati.username)} {if $dati_errati.username == 'username'} {$error_msg.username} {/if}{if $dati_errati.username == 'useresistente'} {$error_msg.useresistente} {/if} {/if}</div><br>
     <img src="./immagini/popcorn22.gif" id="asterisco"><label>Password:</label> <input type="password" id="password" placeholder="Password" size="20" maxlength="40" value="{if isset($dati_registrazione.password)}{$dati_registrazione.password}{/if}" onchange="validazioneadmin('password');"><div id="risultato2">{if isset($dati_errati.password)}{if $dati_errati.password=="TRUE"} {$error_msg.password}{/if} {/if}</div><br>
     <img src="./immagini/popcorn22.gif" id="asterisco"><label>Conferma Password:</label> <input type="password" id="password_1" placeholder="Conferma Password" size="20" maxlength="40" onchange="validazioneadmin('password_1');"><div id="risultato3">{if isset($dati_errati.password)} {$error_msg.password} {/if}</div><br>
     <img src="./immagini/popcorn22.gif" id="asterisco"><label>E-Mail:</label><input type="text" id="email" size="40" maxlength="40" placeholder="Inserisci indirizzo e-mail" value="{if isset($dati_registrazione.email)}{$dati_registrazione.email}{/if}" onchange="validazioneadmin('email');"><div id="risultato4">{if isset($dati_errati.email)}{if $dati_errati.email == "email"} {$error_msg.email} {/if}{if $dati_errati.email == "emailesistente"} {$error_msg.emailesistente} {/if}{/if}</div><br>
     <img src="./immagini/popcorn22.gif" id="asterisco"><label>Nome:</label><input type="text" placeholder="Nome" size="20" maxlength="40" id="nome" value="{if isset($dati_registrazione.nome)}{$dati_registrazione.nome}{/if}"  onchange="validazioneadmin('nome');"><div id="risultato5">{if isset($dati_errati.nome)}{if $dati_errati.nome=="TRUE"}{$error_msg.nome} {/if}{/if}</div><br>
     <img src="./immagini/popcorn22.gif" id="asterisco"><label>Cognome:</label><input type="text" id="cognome" size="20" maxlength="40" placeholder="Cognome" value="{if isset($dati_registrazione.cognome)}{$dati_registrazione.cognome}{/if}" onchange="validazioneadmin('cognome');"><div id="risultato6">{if isset($dati_errati.cognome)} {if $dati_errati.cognome=="TRUE"} {$error_msg.cognome} {/if}{/if}</div><br>
    <script type="text/javascript" src="./JS/dtpk.js"></script>
    <div id="anim"><label>Data di nascita:</label><input type="text" id="data_nascita" size="20" maxlength="20" placeholder="aaaa-mm-gg" value="{if isset($dati_registrazione.data_nascita)}{$dati_registrazione.data_nascita}{/if}"></div><div id="risultato7"></div><br>
    <br>
    <input type="submit" id="submit" value="Registra" onclick="registra_admin();"> 
</div>